### ISSUE TITLE
Failing to install on Raspberry Pi3

### ISSUE THREAD

**Issue by Miq1** [jdillenkofer/camera_proxy#20]
Sorry if this is a noob problem, but I am completely blank on Python, especially on the Raspi. I wanted to set up the camera_proxy on my pihole Raspi, cloned the repository with git and wanted to install the prerequisites. But the very first is failing already:
```
pi@raspberrypi:~/camera_proxy $ sudo pip install av
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting av
  Downloading https://files.pythonhosted.org/packages/40/e6/da37b548e9e1312fb11ffd0f31f8679e1b96d3859790a77e93a113394d34/av-8.0.3.tar.gz (2.3MB)
    100% |████████████████████████████████| 2.3MB 49kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Mwk4pG/av/setup.py", line 9, in <module>
        from shlex import quote
    ImportError: cannot import name quote

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Mwk4pG/av/
```
So it looks like something (``quote``?) is missing, but I do not know how to fix that...

Any help is highly appreciated!

**Comment by Miq1** [comment]
I found I had to use ``pip3`` instead of ``pip`` to install the libraries and ``python3`` to run main.py.
